from django.utils.translation import ugettext_lazy as _

__all__ = (
    'SMS_MESSAGE_DELIVERY_STATUS_PENDING',
    'SMS_MESSAGE_DELIVERY_STATUS_SENT',
    'SMS_MESSAGE_DELIVERY_STATUS_DELIVERED',
    'SMS_MESSAGE_DELIVERY_STATUSES',
)

SMS_MESSAGE_DELIVERY_STATUS_PENDING = 'pending'
SMS_MESSAGE_DELIVERY_STATUS_SENT = 'sent'
SMS_MESSAGE_DELIVERY_STATUS_DELIVERED = 'delivered'

SMS_MESSAGE_DELIVERY_STATUSES = (
    (SMS_MESSAGE_DELIVERY_STATUS_PENDING, _("Pending")),
    (SMS_MESSAGE_DELIVERY_STATUS_SENT, _("Sent")),
    (SMS_MESSAGE_DELIVERY_STATUS_DELIVERED, _("Delivered")),
)
