from django.utils.translation import ugettext_lazy as _

__all__ = (
    'SMS_MESSAGE_DELIVERY_STATUS_PENDING',
    'SMS_MESSAGE_DELIVERY_STATUS_SENT',
    'SMS_MESSAGE_DELIVERY_STATUS_DELIVERED',
    'SMS_MESSAGE_DELIVERY_STATUSES',
)

SMS_MESSAGE_DELIVERY_STATUS_PENDING = 'pending'
SMS_MESSAGE_DELIVERY_STATUS_SENT = 'sent'
SMS_MESSAGE_DELIVERY_STATUS_DELIVERED = 'delivered'

SMS_MESSAGE_DELIVERY_STATUSES = (
    (SMS_MESSAGE_DELIVERY_STATUS_PENDING, _("Pending")),
    (SMS_MESSAGE_DELIVERY_STATUS_SENT, _("Sent")),
    (SMS_MESSAGE_DELIVERY_STATUS_DELIVERED, _("Delivered")),
)

SMS_MESSAGE_PRIORITY_VERY_HIGH = 1
SMS_MESSAGE_PRIORITY_HIGH = 2
SMS_MESSAGE_PRIORITY_MEDIUM = 3
SMS_MESSAGE_PRIORITY_NORMAL = 4
SMS_MESSAGE_PRIORITY_LOW = 5
SMS_MESSAGE_PRIORITY_VERY_LOW = 6

SMS_MESSAGE_PRIORITIES = (
    (SMS_MESSAGE_PRIORITY_VERY_HIGH, "Very high"),
    (SMS_MESSAGE_PRIORITY_HIGH, "High"),
    (SMS_MESSAGE_PRIORITY_MEDIUM, "Medium"),
    (SMS_MESSAGE_PRIORITY_NORMAL, "Normal"),
    (SMS_MESSAGE_PRIORITY_LOW, "Low"),
    (SMS_MESSAGE_PRIORITY_VERY_LOW, "Very low"),
)
