# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import sms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='Unique identifier')),
                ('recipient', models.TextField(help_text='The `to` field in the DMS Receive SMS Interface', verbose_name='Recipient')),
                ('sender', models.CharField(help_text='The `from` field in the DMS Receive SMS Interface', max_length=255, verbose_name='Sender')),
                ('message', models.TextField(help_text='The `text` field in the DMS Receive SMS Interface', verbose_name='Message')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created.', verbose_name='Date created')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='sent', help_text='Message delivery status (if known)', max_length=255, verbose_name='Delivery status')),
                ('date_delivered', models.DateTimeField(blank=True, help_text='Date delivered.', null=True, verbose_name='Date delivered')),
                ('priority', models.IntegerField(blank=True, help_text='The `from` field in the SMS Receive SMS Interface', null=True, verbose_name='Priority')),
                ('arrival_date', models.DateTimeField(blank=True, help_text='Date when the SMS message needs to be sent on.', null=True, verbose_name='Arrival date')),
            ],
            options={
                'verbose_name': 'SMS message',
                'ordering': ['-date_created'],
                'verbose_name_plural': 'SMS messages',
            },
            bases=(models.Model, sms.models.PassMixin),
        ),
    ]
