# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Very high'), (2, 'High'), (3, 'Medium'), (4, 'Normal'), (5, 'Low'), (6, 'Very low')], default=4, help_text='The `from` field in the SMS Receive SMS Interface', null=True, verbose_name='Priority'),
        ),
    ]
