# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='recipient',
            field=models.TextField(help_text='The `to` field in the DMS Receive SMS Interface', verbose_name='Recipient'),
        ),
    ]
